---
title: "git_01"
author: "Anicia Friend"
date: "Spring 2025"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->


  'Twas brillig, and the slithy toves  
Did gyre and gimble in the wabe:  
All mimsy were the borogoves,  
And the mome raths outgrabe.  
"Beware the Jabberwock, my son!  


## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->


MIST- I don't believe the sleepers in the house know where they are.  
SMOKE- They've been here long enough to push the woods back from around the house and part them in the middle with a path.  
MIST- And still I doubt if they know where they are.   And I begin to fear they never will. All they maintain the path for is the comfort of visiting with the equally bewildered.  



## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->


The sun was shining on the sea  
Shining with all his might:  
He did his very best to make  
The billows smooth and bright  And this was odd, because it was  
The middle of the night.  
The moon was shining sulkily,  
Because she thought the sun  
Had got no business to be there  
After the day was done –  
‘It’s very rude of him’ she said,  
‘To come and spoil the fun!  


## Last Verse
<!--Put a short poem you created using chatGPT of 20 to 30 lines,here!-->


Whosever room this is should be ashamed!  
His underwear is hanging on the lamp.  

His raincoat is there in the overstuffed chair,  
And the chair is becoming quite mucky and damp.  

His workbook is wedged in the window,  
His sweater's been thrown on the floor.  

His scarf and one ski are beneath the TV,  
And his pants have been carelessly hung on the door.  

His books are all jammed in the closet,  
His vest has been left in the hall.  

A lizard named Ed is asleep in his bed,  
And his smelly old sock has been stuck to the wall.  

Whosever room this is should be ashamed!  
Donald or Robert or Willie or—  

Huh? You say it’s mine? Oh, dear,  
I knew it looked familiar!  



